# Generated by Django 3.0.5 on 2020-04-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
